In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.set_option('display.max_columns', None)
from datetime import datetime

In [35]:
df = pd.read_csv("igbd_dataset_v1.csv",low_memory=False)

In [36]:
df

,id,name,platforms,first_release_date,category,genres,themes,player_perspectives,rating,rating_count,similar_games,total_rating,total_rating_count,url,aggregated_rating,aggregated_rating_count,year,month,weighted_score,normalized_weighted_score
0,1020.0,GrandTheftAutoV,"6,9,12,48,49",2013-09-17,0.0,"5,10,14,31","1,27,33,38","1,2",91.007003,2783.0,"40,109,733,960,1121,1377,3188,3262,19441",93.423502,2817.0,https://www.igdb.com/games/grand-theft-auto-v,95.840000,34.0,2013.0,9.0,253272.490450,100.000000
1,1942.0,TheWitcher3:WildHunt,"6,48,49",2015-05-19,0.0,"12,31","1,17,38",2,95.708657,2468.0,"121,472,533,1334,1593,1887,3025,9938,11270",93.714329,2494.0,https://www.igdb.com/games/the-witcher-3-wild-...,91.720000,26.0,2015.0,5.0,236208.966262,93.262780
2,72.0,Portal2,"3,6,9,12,14",2011-04-19,0.0,"5,8,9,31","1,18,27",1,91.331534,2116.0,"7350,11646,16992,20342,22387,24426,55173,55190...",91.887989,2129.0,https://www.igdb.com/games/portal-2,92.444444,13.0,2011.0,4.0,193257.526516,76.304192
3,472.0,TheElderScrollsV:Skyrim,"6,9,12",2011-11-11,0.0,"12,31","1,17,33,38","1,2",87.714979,2184.0,"56,59,121,533,538,832,1081,1942,3025",91.913045,2196.0,https://www.igdb.com/games/the-elder-scrolls-v...,96.111111,12.0,2011.0,11.0,191569.514797,75.637711
4,1009.0,TheLastofUs,9,2013-06-14,0.0,"5,31","1,19,21,23",2,94.494275,1835.0,"533,538,1020,1121,1164,1985,2031,11270,19441",93.016368,1851.0,https://www.igdb.com/games/the-last-of-us,91.538462,16.0,2013.0,6.0,173396.994439,68.462625
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122397,36795.0,SuperDoomed'nDamned,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.igdb.com/games/super-doomedn-damned,NaN,NaN,NaN,NaN,NaN,NaN
122398,114314.0,DestleStrike,NaN,NaN,0.0,32,1,NaN,NaN,NaN,"32902,37419,40524,43367,105233,111130,113895,1...",NaN,NaN,https://www.igdb.com/games/destle-strike,NaN,NaN,NaN,NaN,NaN,NaN
122399,115593.0,NextStop3,NaN,NaN,0.0,"13,15",NaN,NaN,NaN,NaN,"17613,36258,51577,55888,65827,76340,79134,1127...",NaN,NaN,https://www.igdb.com/games/next-stop-3,NaN,NaN,NaN,NaN,NaN,NaN
122400,115038.0,\u5e7d\u94c3\u5170-lilyofthehollow-,NaN,NaN,0.0,32,NaN,NaN,NaN,NaN,"8367,74127,81275,102420,108778,111130,113895,1...",NaN,NaN,https://www.igdb.com/games/you-ling-lan-lily-o...,NaN,NaN,NaN,NaN,NaN,NaN
122401,76632.0,[accuwar],82,NaN,0.0,16,39,3,NaN,NaN,NaN,NaN,NaN,https://www.igdb.com/games/accuwar,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
df.index

RangeIndex(start=0, stop=122402, step=1)

In [40]:
df.columns

Index(['id', 'name', 'platforms', 'first_release_date', 'category', 'genres',
       'themes', 'player_perspectives', 'rating', 'rating_count',
       'similar_games', 'total_rating', 'total_rating_count', 'url',
       'aggregated_rating', 'aggregated_rating_count', 'year', 'month',
       'weighted_score', 'normalized_weighted_score'],
      dtype='object')

In [42]:
df.nunique()

id                           122401
name                         119606
platforms                      4364
first_release_date             9833
category                          8
genres                         1755
themes                         1110
player_perspectives              65
rating                         8159
rating_count                    502
similar_games                 33949
total_rating                   8864
total_rating_count              508
url                          122400
aggregated_rating              1399
aggregated_rating_count          39
year                             55
month                            12
weighted_score                 8552
normalized_weighted_score      8515
dtype: int64

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122402 entries, 0 to 122401
Data columns (total 20 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   id                         122401 non-null  float64
 1   name                       122400 non-null  object
 2   platforms                  66051 non-null   object
 3   first_release_date         64068 non-null   object
 4   category                   122401 non-null  float64
 5   genres                     81459 non-null   object
 6   themes                     53573 non-null   object
 7   player_perspectives        33675 non-null   object
 8   rating                     18645 non-null   float64
 9   rating_count               18648 non-null   float64
 10  similar_games              87876 non-null   object
 11  total_rating               18648 non-null   float64
 12  total_rating_count         18648 non-null   float64
 13  url                        122400 non-null  object
 14  aggregated_rating          12417 non-null   float64
 15  aggregated_rating_count    12417 non-null   float64
 16  year                       64068 non-null   float64
 17  month                      64068 non-null   float64
 18  weighted_score             18645 non-null   float64
 19  normalized_weighted_score  18645 non-null   float64
dtypes: float64(12), object(8)
memory usage: 18.7+ MB

In [44]:
df.isnull( ).sum( )

id                                1
name                              2
platforms                     56351
first_release_date            58334
category                          1
genres                        40943
themes                        68829
player_perspectives           88727
rating                       103757
rating_count                 103754
similar_games                 34526
total_rating                 103754
total_rating_count           103754
url                               2
aggregated_rating            109985
aggregated_rating_count      109985
year                          58334
month                         58334
weighted_score               103757
normalized_weighted_score    103757
dtype: int64

In [45]:
df.size

2448040

In [46]:
df.shape

(122402, 20)

In [47]:
df.memory_usage( )

Index                           128
id                           979216
name                         979216
platforms                    979216
first_release_date           979216
category                     979216
genres                       979216
themes                       979216
player_perspectives          979216
rating                       979216
rating_count                 979216
similar_games                979216
total_rating                 979216
total_rating_count           979216
url                          979216
aggregated_rating            979216
aggregated_rating_count      979216
year                         979216
month                        979216
weighted_score               979216
normalized_weighted_score    979216
dtype: int64

In [51]:
df.nlargest(5, 'category')

,id,name,platforms,first_release_date,category,genres,themes,player_perspectives,rating,rating_count,similar_games,total_rating,total_rating_count,url,aggregated_rating,aggregated_rating_count,year,month,weighted_score,normalized_weighted_score
4667,44158.0,Minecraft:StoryMode-SeasonTwo,"6,12,34,39,48,49,130",2017-07-11,7.0,"2,31",27,2,69.331673,11.0,"60,13189,17548,18011,18841,24426,25222,28309,3...",71.715837,13.0,https://www.igdb.com/games/minecraft-story-mod...,74.1,2.0,2017.0,7.0,762.648408,0.301118
47605,24499.0,TomClancy'sRainbowSix:Siege-OperationBlackIce,"6,48,49",2016-02-09,7.0,"5,24","1,39",1,NaN,NaN,"43367,102868,103292,103298,103301,105049,10680...",NaN,NaN,https://www.igdb.com/games/tom-clancys-rainbow...,NaN,NaN,2016.0,2.0,NaN,NaN
48128,24500.0,TomClancy'sRainbowSix:Siege-OperationDustLine,"6,48,49",2016-05-10,7.0,"5,24","1,39",1,NaN,NaN,"43367,102868,103292,103298,103301,105049,10680...",NaN,NaN,https://www.igdb.com/games/tom-clancys-rainbow...,NaN,NaN,2016.0,5.0,NaN,NaN
48758,23176.0,TomClancy'sRainbowSix:Siege-OperationSkullRain,"6,48,49",2016-08-09,7.0,"5,24","1,39",1,NaN,NaN,"43367,102868,103292,103298,103301,105049,10680...",NaN,NaN,https://www.igdb.com/games/tom-clancys-rainbow...,NaN,NaN,2016.0,8.0,NaN,NaN
49838,25641.0,TomClancy'sRainbowSix:Siege-OperationRedCrow,"6,48,49",2016-11-24,7.0,"5,24","1,39",1,NaN,NaN,"43367,102868,103292,103298,103301,105049,10680...",NaN,NaN,https://www.igdb.com/games/tom-clancys-rainbow...,NaN,NaN,2016.0,11.0,NaN,NaN

In [52]:
df.isna( )

,id,name,platforms,first_release_date,category,genres,themes,player_perspectives,rating,rating_count,similar_games,total_rating,total_rating_count,url,aggregated_rating,aggregated_rating_count,year,month,weighted_score,normalized_weighted_score
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122397,False,False,True,True,False,True,True,True,True,True,True,True,True,False,True,True,True,True,True,True
122398,False,False,True,True,False,False,False,True,True,True,False,True,True,False,True,True,True,True,True,True
122399,False,False,True,True,False,False,True,True,True,True,False,True,True,False,True,True,True,True,True,True
122400,False,False,True,True,False,False,True,True,True,True,False,True,True,False,True,True,True,True,True,True
122401,False,False,False,True,False,False,False,False,True,True,True,True,True,False,True,True,True,True,True,True

In [54]:
df['name'].value_counts()

Warhammer40                     62
Tennis                          14
I                               10
Pinball                          9
WheelofFortune                   9
                                ..
MonsterHunterDualPack            1
BeastBall                        1
DarkSouls:Collector'sEdition     1
FlightControlRocket              1
[accuwar]                        1
Name: name, Length: 119606, dtype: int64

In [13]:
n = 5

for i in range(1,n+1):
    print(i)

1
2
3
4
5

In [20]:
n = 5

for i in range(1,n+1):
    for j in range(1,n+1-i):
        print('', end = '')
    for k in range(1, i+1):
        print(k, end = '')
    for l in range(i-1,0,-1):
        print(l, end = '')
    print()

1
121
12321
1234321
123454321

In [28]:
n = 5

for i in range(1,n+1):
    for j in range(1,n+1-i):
        print('', end = '')

In [25]:
    for l in range(i-1,0,-1):
        print(l, end = '')

4321

In [26]:
    for k in range(1, i+1):
        print(k, end = '')

12345

In [32]:
n = 5

for i in range(1, 6):
    for j in range(1,n+1-i):
        print(j, end= '')
    for k in range(1,i+1):
        print(k, end= '')
    print()

12341
12312
12123
11234
12345